services:
  backend:
    build: ./backend
    ports:
      - '3006:3000'
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - '5176:80'
    depends_on:
      - backend
